In [5]:
import numpy as np
from sqlalchemy.sql.operators import truediv

In [ ]:
np1=np.diag([9,9,9])
print("The 3d array with nines diagonal :\n ",np1)

The 3d array with nines diagonal :  [[9 0 0]
 [0 9 0]
 [0 0 9]]


In [22]:
np2=np.arange(2,33,2)
new=np2.reshape(4,4)
mean=np.mean(new)
std=np.std(new)

condition = (new > (mean - 0.5 * std)) & (new < (mean + 0.5 * std))
filtered = new[condition]
print("\n Filtered values within 1/2 std of mean:\n ", filtered)


 Filtered values within 1/2 std of mean:
  [14 16 18 20]


In [30]:
np3=np.zeros((9,9),dtype=int)
print("\n Here is the zeros Array :\n ",np3)



 Here is the zeros Array :
  [[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


In [38]:
n=int(input("Enter the number N : "))
np4=np.arange(1,n+1,1)
new=np4.reshape(1,n)*np.ones((n,1),dtype=int)
print(f"\n Here is the {n}*{n} broadcasted Array :\n ",new)


 Here is the 4*4 broadcasted Array :
  [[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [41]:
#Problem 1 :
n=int (input())
list=list(map(int,input().split()))

seraj_score=0
dema_score=0

left=0
right=n-1

for turn in range(n) :
    if list[left] > list[right] :
        chosen=list[left]
        left+=1
    else :
        chosen=list[right]
        right-=1
    if turn %2==0 :
        seraj_score+= chosen
    else :
        dema_score+= chosen

print(seraj_score,dema_score)


KeyboardInterrupt: Interrupted by user

In [42]:
#problem 2 :
n, m=map(int,input().split())
pixels={'C','M','Y'}
isColored=False

for _ in range(n):
    row=input().split()
    for pixel in row :
         if pixel in pixels :
             isColored=True
             break
    if isColored :
        break

print("#Color"if isColored else "#Black&White")

ValueError: invalid literal for int() with base 10: 'C'