In [1]:
#import Libraries
import pandas as pd
import numpy as np


In [2]:
#read csv
df = pd.read_csv('train_blackFriday.csv')
df

User_ID Product_ID Gender    Age  Occupation City_Category  \
0       1000001  P00069042      F   0-17          10             A   
1       1000001  P00248942      F   0-17          10             A   
2       1000001  P00087842      F   0-17          10             A   
3       1000001  P00085442      F   0-17          10             A   
4       1000002  P00285442      M    55+          16             C   
...         ...        ...    ...    ...         ...           ...   
550063  1006033  P00372445      M  51-55          13             B   
550064  1006035  P00375436      F  26-35           1             C   
550065  1006036  P00375436      F  26-35          15             B   
550066  1006038  P00375436      F    55+           1             C   
550067  1006039  P00371644      F  46-50           0             B   

       Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                               2               0                   3   
1                               2               0                   1   
2                               2               0                  12   
3                               2               0                  12   
4                              4+               0                   8   
...                           ...             ...                 ...   
550063                          1               1                  20   
550064                          3               0                  20   
550065                         4+               1                  20   
550066                          2               0                  20   
550067                         4+               1                  20   

        Product_Category_2  Product_Category_3  Purchase  
0                      NaN                 NaN      8370  
1                      6.0                14.0     15200  
2                      NaN                 NaN      1422  
3                     14.0                 NaN      1057  
4                      NaN                 NaN      7969  
...                    ...                 ...       ...  
550063                 NaN                 NaN       368  
550064                 NaN                 NaN       371  
550065                 NaN                 NaN       137  
550066                 NaN                 NaN       365  
550067                 NaN                 NaN       490  

[550068 rows x 12 columns]

In [3]:
#number of rows and coulmns
df.shape

(550068, 12)

In [4]:
#show data types found
df.dtypes

User_ID                         int64
Product_ID                     object
Gender                         object
Age                            object
Occupation                      int64
City_Category                  object
Stay_In_Current_City_Years     object
Marital_Status                  int64
Product_Category_1              int64
Product_Category_2            float64
Product_Category_3            float64
Purchase                        int64
dtype: object

In [5]:
#show coulmns
df.columns

Index(['User_ID', 'Product_ID', 'Gender', 'Age', 'Occupation', 'City_Category',
       'Stay_In_Current_City_Years', 'Marital_Status', 'Product_Category_1',
       'Product_Category_2', 'Product_Category_3', 'Purchase'],
      dtype='object')

In [6]:
#Checking NaN values in the given dataset
df.isnull().sum()

User_ID                            0
Product_ID                         0
Gender                             0
Age                                0
Occupation                         0
City_Category                      0
Stay_In_Current_City_Years         0
Marital_Status                     0
Product_Category_1                 0
Product_Category_2            173638
Product_Category_3            383247
Purchase                           0
dtype: int64

In [7]:
#Checking duplicate values in the dataset
df.duplicated().sum()

0

In [9]:
#Renaming the column name to lower case
df.columns  = df.columns.str.lower()
df.columns

Index(['user_id', 'product_id', 'gender', 'age', 'occupation', 'city_category',
       'stay_in_current_city_years', 'marital_status', 'product_category_1',
       'product_category_2', 'product_category_3', 'purchase'],
      dtype='object')

In [10]:
#Removing Reducant Values (user id)
df.drop(['user_id'], axis=1,inplace=True)

In [11]:
#Checking for unique values in each individual column of the dataset
df.nunique()

product_id                     3631
gender                            2
age                               7
occupation                       21
city_category                     3
stay_in_current_city_years        5
marital_status                    2
product_category_1               20
product_category_2               17
product_category_3               15
purchase                      18105
dtype: int64

In [12]:
for column in df.columns:
    print(f"Unique Values in {column}: {df[column].nunique()}")

Unique Values in product_id: 3631
Unique Values in gender: 2
Unique Values in age: 7
Unique Values in occupation: 21
Unique Values in city_category: 3
Unique Values in stay_in_current_city_years: 5
Unique Values in marital_status: 2
Unique Values in product_category_1: 20
Unique Values in product_category_2: 17
Unique Values in product_category_3: 15
Unique Values in purchase: 18105


In [13]:
for column in df.columns:
    print(f"Unique Values in {column}: {df[column].unique()}")

Unique Values in product_id: ['P00069042' 'P00248942' 'P00087842' ... 'P00370293' 'P00371644'
 'P00370853']
Unique Values in gender: ['F' 'M']
Unique Values in age: ['0-17' '55+' '26-35' '46-50' '51-55' '36-45' '18-25']
Unique Values in occupation: [10 16 15  7 20  9  1 12 17  0  3  4 11  8 19  2 18  5 14 13  6]
Unique Values in city_category: ['A' 'C' 'B']
Unique Values in stay_in_current_city_years: ['2' '4+' '3' '1' '0']
Unique Values in marital_status: [0 1]
Unique Values in product_category_1: [ 3  1 12  8  5  4  2  6 14 11 13 15  7 16 18 10 17  9 20 19]
Unique Values in product_category_2: [nan  6. 14.  2.  8. 15. 16. 11.  5.  3.  4. 12.  9. 10. 17. 13.  7. 18.]
Unique Values in product_category_3: [nan 14. 17.  5.  4. 16. 15.  8.  9. 13.  6. 12.  3. 18. 11. 10.]
Unique Values in purchase: [ 8370 15200  1422 ...   135   123   613]


In [14]:
#replace each range in age coulmn to its creosspond category ex:0-17 ->child ,18-25 ->teenage, 26-50 -> adult , 51-55+ ->old

age_map = {
    '0-17': 'Child',
    '18-25': 'Young Adult',
    '26-35': 'Adult',
    '36-45': 'Mid Adult',
    '46-50': 'Senior Adult',
    '51-55': 'Senior',
    '55+': 'Elderly'
}
df['age_group'] = df['age'].map(age_map)

In [15]:
df['stay_in_current_city_years'] = df['stay_in_current_city_years'].str.replace('+', '').astype(int)

In [64]:
df['product_category_2'].fillna(0, inplace=True)
df['product_category_3'].fillna(0, inplace=True)


C:\Users\SAFAA\AppData\Local\Temp\ipykernel_1300\3979036528.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['product_category_2'].fillna(0, inplace=True)
C:\Users\SAFAA\AppData\Local\Temp\ipykernel_1300\3979036528.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For examp

In [18]:
df['product_category_2'] = df['product_category_2'].astype(int)
df['product_category_3'] = df['product_category_3'].astype(int)

In [21]:
#Checking for unique values for city_years column
df['city_category'].unique()

array(['A', 'C', 'B'], dtype=object)

In [70]:
#remove + from rows in city_years column
df['stay_in_current_city_years'] = df['stay_in_current_city_years'].astype(str)
df['stay_in_current_city_years'] = (
    df['stay_in_current_city_years']
    .str.replace('+', '', regex=False)
    .replace('', np.nan)
    .astype(float)
    .astype('Int64')
)

In [32]:
#Checking for unique values for category_1 column
df['product_category_1'].unique()

array([ 3,  1, 12,  8,  5,  4,  2,  6, 14, 11, 13, 15,  7, 16, 18, 10, 17,
        9, 20, 19], dtype=int64)

In [33]:
#Checking for unique values for category_2 column
df['product_category_2'].unique()

array([ 0,  6, 14,  2,  8, 15, 16, 11,  5,  3,  4, 12,  9, 10, 17, 13,  7,
       18])

In [35]:
#fill null you found
df['product_category_2'] = df['product_category_2'].fillna(0)
df['product_category_2'].unique()

array([ 0,  6, 14,  2,  8, 15, 16, 11,  5,  3,  4, 12,  9, 10, 17, 13,  7,
       18])

In [36]:
#Checking for unique values for category_3 column
df['product_category_3'].unique()

array([ 0, 14, 17,  5,  4, 16, 15,  8,  9, 13,  6, 12,  3, 18, 11, 10])

In [37]:
#fill null you found
df['product_category_3'] =df['product_category_3'].fillna(0)

In [38]:
df['product_category_3'].unique()

array([ 0, 14, 17,  5,  4, 16, 15,  8,  9, 13,  6, 12,  3, 18, 11, 10])

In [39]:
#check for null values
df.isnull().sum()

product_id                    0
gender                        0
age                           0
occupation                    0
city_category                 0
stay_in_current_city_years    0
marital_status                0
product_category_1            0
product_category_2            0
product_category_3            0
purchase                      0
age_group                     0
dtype: int64

In [73]:
#check for duplicates values
df.duplicated().sum()

516